<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTtavtvi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTtavtvi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTtavtvi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTtavtvi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTtavtvi\appDevDebugProjectContainer([
    'container.build_hash' => 'Ttavtvi',
    'container.build_id' => 'b270e2a0',
    'container.build_time' => 1635760391,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTtavtvi');
