version: '3.6'

services:

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - "./nginx/:/etc/nginx/templates/"
      - ./src:/var/www/html:rw,cached
      - ./certs:/etc/certs
    environment:
      - "NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf"
      - "DOMAIN=${DOMAIN}"
    depends_on:
      - php
    restart: always

  mysql:
    image: mysql:8.0.21
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    container_name: ${APP_NAME}-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql:delegated
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-php
    volumes:
      - ./src/:/var/www/html
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql
    restart: always

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    links:
      - mysql
    volumes:
      - ./etc/php/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8082:80

  mailhog:
    container_name: ${APP_NAME}-mailhog
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"