<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'democqrshooksusage.domain.reviewer.query_handler.get_reviewer_settings_for_form_handler' shared service.

return $this->services['democqrshooksusage.domain.reviewer.query_handler.get_reviewer_settings_for_form_handler'] = new \DemoCQRSHooksUsage\Domain\Reviewer\QueryHandler\GetReviewerSettingsForFormHandler(${($_ = isset($this->services['democqrshooksusage.repository.reviewer']) ? $this->services['democqrshooksusage.repository.reviewer'] : $this->load('getDemocqrshooksusage_Repository_ReviewerService.php')) && false ?: '_'});
