<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIjlxrmx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIjlxrmx/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIjlxrmx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerIjlxrmx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerIjlxrmx\appProdProjectContainer([
    'container.build_hash' => 'Ijlxrmx',
    'container.build_id' => 'ff3851ec',
    'container.build_time' => 1635416432,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIjlxrmx');
