<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'democqrshooksusage.domain.reviewer.command_handler.update_is_allowed_to_review_handler' shared service.

return $this->services['democqrshooksusage.domain.reviewer.command_handler.update_is_allowed_to_review_handler'] = new \DemoCQRSHooksUsage\Domain\Reviewer\CommandHandler\UpdateIsAllowedToReviewHandler(${($_ = isset($this->services['democqrshooksusage.repository.reviewer']) ? $this->services['democqrshooksusage.repository.reviewer'] : $this->load('getDemocqrshooksusage_Repository_ReviewerService.php')) && false ?: '_'});
