<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerByxvfdr\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerByxvfdr/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerByxvfdr.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerByxvfdr\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerByxvfdr\appProdProjectContainer([
    'container.build_hash' => 'Byxvfdr',
    'container.build_id' => '7a14fdd7',
    'container.build_time' => 1635416432,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerByxvfdr');
